version: '3.8'

services:
  discourse:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      RAILS_ENV: production
      DISCOURSE_DB_HOST: postgres
      DISCOURSE_DB_PORT: 5432
      DISCOURSE_DB_NAME: discourse
      DISCOURSE_DB_USERNAME: discourse
      DISCOURSE_DB_PASSWORD: discourse_password
      DISCOURSE_REDIS_HOST: redis
      DISCOURSE_REDIS_PORT: 6379
      DISCOURSE_HOSTNAME: localhost
      DISCOURSE_PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - discourse_uploads:/app/public/uploads
      - discourse_backups:/app/public/backups
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  discourse_uploads:
  discourse_backups: 