version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg16 # 使用内置了 pgvector 的镜像
    container_name: pg-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    networks:
      - dify
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:

networks:
  dify:
    external: true
