version: "3"
services:
    redis:
      image: redis:latest
      container_name: redis_master
      restart: always
      volumes:
        - ./redis-data:/data
      command: '--requirepass difyai123456'
      ports:
        - 6379:6379
      networks:
        - dify
networks:
  dify:
    external: true
